### ISSUE TITLE
VAD is not a constructor?

### ISSUE THREAD

**Issue by rizwanishaq** [serenadeai/webrtcvad#1]
Hi,
I am trying to use your webrtcvad like
const VAD = require("webrtcvad");
const vad = new VAD(8000, 3);

but it is giving me the following error 
TypeError: VAD is not a constructor

any solution for this?

**Comment by tmacwill** [comment]
thanks for the report! when using his library with `require`, you'll need to do `const VAD = require("webrtcvad").default`. let me know if that works for you!

**Comment by rizwanishaq** [comment]
Thanks, it is working now.
